BlitterStudio/amiberry

src/main.cpp
src/od-pandora/pandora.cpp
src/od-pandora/pandora_gui.cpp
src/pandora.cpp

Simplified the LED status code.
Removed the excess code from gui_flicker_led()  which now just passes straight into gui_led()

Simplified LED status code

---

src/cfgfile.cpp

As title. Painstakingly reformatted this file so all functions adhere to same formatting standards. Should make it more legible.

Reformatted cfgfile.cpp to make it more legible

---

Makefile

Added the target for Odroid XU4.
Not sure whether there are better/more flags.
Feel free to add things to test/fix before accepting this request.
Things possibly broken:

Support for Odroid XU4

---

Makefile

Activates render thread for target xu4

---

Makefile

Fixes # .
None reported.
Just adding support to build Amiberry on the OSMC box "Vero4K".
Thanks.
@midwan

Added Vero4K build support.

---

src/osdep/amiberry_whdbooter.cpp

Fixes # Unreported WHDLoad second controller bug
- 1 minor change

Bugfix for 2nd controller selection

---

Makefile

Fixes # .
-add platrom sun8i
@midwan

add platform sun8i

---

src/jit/compemu.cpp

Fixes src\jit\compemu.cpp
- fixed JIT: link.l sp,#, link.w sp,# and unlk sp (LINK.L, LINK.W, UNLK.L)
not really heavy used on amigaos, but at least this fixes cputest
- fixed JIT: EORSR.B and ORSR.B, now WB 3.9 shell should work well when JIT enabled
Hi,
I used amiberry for a while on a raspberry p2 with JIT enabled and found that OS 3.9 shell does not work well, sometimes output text freeze and you have to click with mouse out of the shell to resume the text output. Sometimes the shell close unexpected.
I've made some test and found that EORSR.B and ORSR.B seems to be buggy.
Since I love Amiga and emulators I suggest these fixes.
P.S.: congrats for your great work with this emulator.
Thanks,
Sante

proposing fix to JIT

---

.gitignore
Android.mk
src/custom.cpp
src/osdep/amiberry.cpp
src/osdep/amiberry_filesys.cpp
src/osdep/amiberry_filesys.hpp
src/osdep/amiberry_mem.cpp
src/osdep/gui/PanelAbout.cpp
src/osdep/gui/PanelHD.cpp
src/osdep/gui/main_window.cpp
src/osdep/writelog.cpp

... if amiberry assets are present on the device. Currently one has to put them there on their own.

Amiberry GUI on Android comes up

---

.gitignore
Android.mk
src/custom.cpp
src/osdep/amiberry.cpp
src/osdep/amiberry_filesys.cpp
src/osdep/amiberry_filesys.hpp
src/osdep/amiberry_mem.cpp
src/osdep/gui/PanelAbout.cpp
src/osdep/gui/PanelHD.cpp
src/osdep/gui/main_window.cpp
src/osdep/writelog.cpp

Fixes Android crash when leaving guisan and starting emulation.
see lengthy commit message :)
@midwan

Fixes Android crash when leaving guisan

---

src/osdep/writelog.cpp

Adds missing `va_end(parms)` for write_log

---

src/osdep/amiberry_whdbooter.cpp

to enable smart centering from @HoraceAndTheSpider's XML.
Two new parameters will be added very soon to the XML (SCREEN_CENTERH= / SCREEN_CENTERV=) which could take 2 values "SMART" or "NONE". 
I was tired of ticking the boxes by hands during all my tests :-p
@midwan

XML: to add smart centering parameters.

---

src/osdep/amiberry_mem.cpp
src/osdep/target.h

Fixes # .
Update for some changes needed to allow code to build with m1 Mac with macOS 13.
Update to version number to work with Apple signing script.
@midwan

macOs updates

---

src/osdep/amiberry_input.cpp

Use string.append() where possible, see if this helps with a rare RetroPie crash
Fixes #1163 .

Refactor controller initialization steps (fixes #1163)

---

CMakeLists.txt
Makefile
src/a2065.cpp
src/cfgfile.cpp
src/devices.cpp
src/ethernet.cpp
src/expansion.cpp
src/include/sana2.h
src/include/uae/slirp.h
src/osdep/amiberry.cpp
src/osdep/amiberry_uaenet.cpp
src/osdep/sysconfig.h
src/savestate.cpp

Added A2065 support.
No SLIRP mode yet, so I'm not sure how this will function in real-life scenarios. It does show up in ShowConfig normally at least.
Fixes #1185  .

feat: Implemented A2065 support (fixes #1185)

---

src/osdep/gui/PanelDisplay.cpp

Add FPS Adjustment options to the Display panel

---

src/osdep/amiberry_input.cpp

Fixes Alt-Tab would leave the keys in a pressed state inside the emulation

Alt tab release

---

src/osdep/amiberry_serial.cpp

Fixes #1494 
Serial port support was broken

1494 hardware serial support broken by v565

---

docs/README.md

I added Amiberry Homebrew cask to Homebrew casks, and opened a pull request on https://github.com/Homebrew/homebrew-cask/pull/198721
Please merge this REAME.md change (or edit it as you want) after then the pull request above is approved.

README.md is updated for Homebrew cask.

---

src/osdep/amiberry_gfx.cpp
src/osdep/amiberry_gfx.h
src/osdep/gui/PanelDisplay.cpp

- Show full screen modes detected by SDL2 in the dropdown
- show available refresh rates

Improve fullscreen modes

---

CMakeLists.txt
cmake/Dependencies.cmake
cmake/SourceFiles.cmake
external/floppybridge/src/SerialIO.cpp
external/floppybridge/src/SuperCardProInterface.cpp
src/cd32_fmv.cpp
src/devices.cpp
src/expansion.cpp
src/include/serial.h
src/osdep/amiberry.cpp
src/osdep/amiberry_input.cpp
src/osdep/amiberry_serial.cpp
src/osdep/picasso96.cpp
src/osdep/sigsegv_handler.cpp
src/osdep/sysconfig.h
src/parser.cpp

- Make external dependencies optional in CMake, to allow for minimal builds

refactor: make external libraries optional

---

src/osdep/amiberry.cpp
src/osdep/amiberry_gui.cpp
src/osdep/gui/gui_handling.h

enhancement: add a default Dark theme (fixes #1639)

---

packaging/linux/Amiberry.desktop
src/filesys.cpp

- fix bug in action_read_link
- add StartupWMClass = amiberry to Amiberry.desktop

fix src/filesys.cpp:action_read_link crash

---

src/bsdsocket.cpp
src/osdep/bsdsocket_host.cpp

Fixes some bsdsocket emulation bugs

fix bsdsocket fdcallback crash

---

src/osdep/amiberry_gui.cpp

Fixes # .
this updates amiberry_gui.cpp to run a check and if it can't find the font it will show an error message and abort rather than seg fault
@midwan

Add more logging for failing to find a font

---

src/osdep/picasso96.cpp

Optimize P96 screen refreshes, by only updating lines that got modified, instead of full-screen redraws.
This helps with the performance especially on lower-powered devices, as it reduces CPU usage when P96 screen modes are used.

P96 improvements
