- src/cfgfile.cpp
- src/include/options.h
- src/inputdevice.cpp
- src/od-pandora/gui/PanelInput.cpp
- src/od-pandora/pandora.cpp
Here are my modifications to allow the use of Joystick buttons to enter the menu and exit the emulator.
I have separated out the Key for Menu/Quit from Joystick Button Menu/Quit to make it easier to handle the options in the handle_msgpump method, i.e. we don't have to worry about clashing int values between SDLK and jbutton.button.
> Quit Button Enhancement

- src/osdep/pandora_input.cpp
Hi
This fixes the CD32 blue button, which doesnt work when joyportXmode=cd32joy is selected ... 
INPUTEVENT_JOY2_CD32_BLUE does not work, but can be replaced with INPUTEVENT_JOY2_2ND_BUTTON , which operates correctly in djoy mode (acting as 2nd button/right mouse button) but also automatically corrects to 'Blue' n cd32joy mode.
This also requires additional fixes to the ad-hoc PS3 mapping code in order to work correctly there, which are included.
> Fixing PS3 Pad Mapping

- src/osdep/amiberry_filesys.cpp
See documentation for open:
https://linux.die.net/man/2/open
> mode specifies the permissions to use in case a new file is created. This argument must be supplied when O_CREAT is specified in flags; if O_CREAT is not specified, then mode is ignored. The effective permissions are modified by the process's umask in the usual way: The permissions of the created file are (mode & ~umask). Note that this mode only applies to future accesses of the newly created file; the open() call that creates a read-only file may well return a read/write file descriptor.
> Fixes a crash due to missing mode with WHDload

- src/osdep/amiberry_gfx.cpp
std::ceil requires cmath header to build correctly on Raspbian Jessie (gcc 4.9.2).
> amiberry_gfx: fix sdl2-dispmanx build

- .gitignore
- Makefile
- src/fpp_native.cpp
Currently amiberry cannot be build for xu4
TODO:
- Adds `HAVE_NEON` to Makefile (odroid uses NEON compatible processors)
- Adds some files gitignore
@midwan
> WIP: Odroid fix

- src/osdep/amiberry_input.cpp
Fixes standalone retroarch hotkeys for quit/menu/reset.
- In Retroarch it's possible to set the "input_enable_hotkey_btn" to "nul", which means you no longer have to hold down a button first before being able to use the other retroarch hotkey buttons. This is useful if you have a dedicated button on your arcade cab for exiting the current game, for example. This code change detects if you don't have anything bound to the hotkey enable button and allows any bound standalone buttons to work.
@midwan
> Support standalone (single button) retroarch hotkeys for quit/menu/reset

- src/osdep/amiberry_gfx.cpp
- src/osdep/gui/main_window.cpp
SDL_SetRelativeMouseMode applies only to sdl1
@midwan
> fix sdl1 build

- src/main.cpp
- src/osdep/gui/PanelPaths.cpp
- src/osdep/gui/gui_handling.h
* Bugfix for 2nd controller selection
* ignore netbeans project
* Add experimental `-autocd=` loading of files (.cue works very well - .iso should also)
* CD Autoloading adapted to include .uae file check and hostconf controller options
* Beginning of Booter Panel implentation
* Booter Panel development .. start on XML reading for picked LHA file
* New WHDLoad booter, included updated boot-data.zip, plus new hostprefs FIXED_HEIGHT= option and bugfixes for XML reading, and symlink ROM scan. Plus updated XML
* Upload of .RTB files that need to accompany the Symlinked Kickstarts, for WHDLoad compatibility.
* Allows for additional libraries from `boot-data.zip` to be linked on load, to aid compatibility (e.g. Dungeon Master), plus new XML
* Fix hardware settings tab issues from XML reading, …
> WHDLoad Booter additional downloads (#435)

- Makefile
- src/main.cpp
- src/osdep/amiberry_gfx.cpp
@midwan
Fixes #492 
It appears that a few controllers require a bit longer to come up to speed than others.
By the time the config is loaded at startup and tries to use the specified controller it isn't ready yet and the settings are ignored.
By the time manual loading of the config is attempted via the GUI the controller is good to go.
---
The affected controllers were ok under SDL1.
With the move to SDL2 the initialisation happens during a later graphics setup phase.  I'm sure there are reasons why it was moved and it's been mostly harmless taking the joystick initialisation with it.
My change is to separately initialise the joystick subsystem at the earlier time that was proven to work for SLD1.2 and then initialise everything else later.
As an …
> Fix #492.  Init Joysticks earlier under SDL2.  Build for armv7 on Vero4k.

- Makefile
Add some common platforms for widely used Amlogic & Rockchip SoCs like:
- Amlogic S905/S905X/S912/S905X2/S922X/A311D
- Rockchip RK3288/RK3328/RK3399
this allows to build Amiberry specific for a SoC and not specific for a SBC.
@midwan 
**This is a first draft**. I added quite similar platforms to some libretro cores before like [mupen64plus-nx](https://github.com/libretro/mupen64plus-libretro-nx/commit/206c08746047160a604530ad40d019a45b4338aa) & would like to get rid of downstream platform patches for amiberry too. I know that AMLG12 devices are buggy at the moment probably because the new GPU of the SoCs need some extra work and extra flags.
> Makefile: added common Amlogic & Rockchip platforms

- src/include/inputdevice.h
- src/inputdevice.cpp
- src/memory.cpp
- src/osdep/amiberry.cpp
- src/osdep/amiberry_input.cpp
- src/osdep/gui/PanelCustom.cpp
These are tweaks and fixes to allow a better experience when using retropie using iPAC and more than one joystick/player connected to the ipac keyboard. In short this now allows me to play 2 player amiga emulation on my arcade cabinet without having to plug anything in!
Fixes # .
-It allows 2 retroarch joysticks to be recognised on one keyboard plugged in, if the retroarch config file has 2 players on one keyboard it will automatically create another keyboard which can be selected in "Input"
-Retro arch keyboard as joystick now exits the emulator and opens the menu using hotkeys
-It allows a generic setting which overrides the mouse speed for all games, this can be changed in amiberry.conf using "input_default_mouse_speed=45", the default is 100 as …
> Fixes to allow Retroarch Keyboard as Joystick to work as > 1 joystick.

- Makefile
RK3399 / RockPro64 had a bit stuttering in scrolling (really noticeable
for example in Pinball Fantasies) and status line seems to be
flickering.
At least for me disabling render thread improvent scrolling considerably
and fixed the flickering in status line.
Fixes #572.
- Disable render thread on PINE64 RockPro64 / RK3399 platform
@midwan
> Disable render thread in RK3399 (RockPro64) target for smoother graphics

- src/osdep/amiberry_whdbooter.cpp
To implement AUTO-HEIGHT setting from XML. 
Examples:
* AUTO-HEIGHT is useful in Agony for instance where screens heights are consistent between intro screens and main game screen (no cut-off).
* AUTO-HEIGHT is better `off` in Blood Money where the intro screen will be cut-off or appear "weird". 
=> in such case a `HEIGHT=` value is preferred.
At this stage, AUTO-HEIGHT is `off` by default and switched to `on` whenever explicitly set in XML **or** in case game entry lacks HEIGHT value.
> WHDBooter: implement AUTO-HEIGHT from XML

- Makefile
- Add AMLSM1 platform string in Makefile
- Builds properly against Cortex-A55
- Should work fine on HardKernel Odroid C4 and Khadas VIM3L
@midwan
> Add support for HardKernel ODroid C4 and Khadas VIM3L (AMLSM1 SoCs)

- Makefile
Fixes previous PR, sorry for that .
- Do not use render thread
- Do not add CPU flags only valid for AArch32
@midwan
> Fix SM1 flags mistake

- src/include/options.h
reduce default_sound_buffer - get rid of laggy sound, works nice on my RPi3!
@midwan
> reduce default_sound_buffer from laggy 16384 to 2048.

- src/osdep/amiberry_whdbooter.cpp
Fixes #729.
The use of `_stprintf(whd_bootscript, "%s more stuff", whd_bootscript)` was unsafe.
It erased content in `whd_bootscript` that was previously written.
> whdload: bug fix in writing bootscript.

- Makefile
Fixes cross compilation. When you build amiberry in a build root that has special build tools for specific targets e.g. https://github.com/SupervisedThinking/LibreELEC-RR/blob/master-rr/packages/supervisedthinking/emulation/standalone/amiberry/package.mk build will fail because host `as` will be used:
```
as: unrecognized option '-mfloat-abi=hard'
make: *** [Makefile:447: src/osdep/neon_helper.o] Error 1
make: *** Waiting for unfinished jobs....
```
only define AS if AS wasn't already defined so change `AS     = as` to `AS     ?= as` so the toolchain `as` will be used instead of host `as`
@midwan
> Makefile: fix cross compile

- Makefile
RPI3 uses Cortex-A53 CPU.
RPI4 uses Cortex-A72 CPU.
The -mcpu flag passed in pi64 and dispmanx variants are incorrect for pi3.
- Split rpi3 and rpi4 64-bit builds
@midwan I think this should be merged before 4.1.5 release.
> Split rpi3/rpi4 64-bit builds to fix -mcpu wrong flag

- Makefile
I have two suggestions for making integration of Amiberry to systems like Batocera a bit easier (at least in my humble opinion). Here's the first one changing `Makefile` with two commits.
- Make `CPUFLAGS` assignment in `a64` platform conditional. This would make it easy to use `a64` as target with CPUFLAGS given to make as needed. First I was making a new `RK3399-64` target for 64-bit RockPro64, but then I thought to suggest this and hear you think about it. The default `CPUFLAGS=-mcpu=cortex-a53` does work with RockPro64 fine. This just adds option for fine tuning if one wants to do it.
- Add new `USE_LD` conditional variable which defaults to `gold` (so by default it should work as before). This is for Batocera integration, but could be usable …
> Makefile changes to make integration to systems like Batocera a bit easier

- src/main.cpp
- src/osdep/amiberry.cpp
Here's another suggestion for making integration of Amiberry to systems like Batocera easier. It may also be beneficial to users in general.
- the 1st commit refactoring existing code to prepare for adding `-o` command line option
- the 2nd commit adds `-o` command line option that can be used to set amiberry.conf values on command line (much line `-s` option).  Any found `-o` options are removed after parsing so that the "old" parser in `real_main()` doesn't trip on them. This makes integration to Batocera and alike easier and may also benefit users in general.
- the 3rd commit make all paths configurable via `amiberry.conf` and the new `-o` option. This makes integration to Batocera and alike easier as they have very specific paths and have used …
> Make amiberry.conf options usable via command line and make all paths configurable

- src/floppybridge/floppybridge_abstract.h
Build fails when using GCC 11 to build Amiberry because NULL is not
in floppybridge_abstract.h. Noticed this when building latest master for
Batocera.
Fixed by including <cstddef> in floppybridge_abstract.h.
See also PR in upstream:
https://github.com/RobSmithDev/FloppyDriveBridge/pull/7
Build error from Batocera for reference:
/rk3399/host/bin/aarch64-buildroot-linux-gnu-g++ -mcpu=cortex-a53 -mabi=lp64 -pipe -Wno-shift-overflow -Wno-narrowing -O3  -std=gnu++14 -MD -MT src/floppybridge/floppybridge_lib.o -MF src/floppybridge/floppybridge_lib.d -I/rk3399/host/aarch64-buildroot-linux-gnu/sysroot/usr/bin/../../usr/include/SDL2 -D_REENTRANT -Iexternal/libguisan/include -Isrc -Isrc/osdep -Isrc/threaddep -Isrc/include -Isrc/archivers -DAMIBERRY -D_FILE_OFFSET_BITS=64 -DCPU_AARCH64  -c -o …
> Fix build failure with GCC 11 in floppybridge

- src/custom.cpp
vsyncmintime and rpt (and read_processor_time()) types are of type
frame_time_t, which is typedef unsigned long frame_time_t. The default
data model on aarch64-gcc seems to be LP64 (at least on Batocera /
Buildroot) which makes int 32-bits and long 64-bits. This causes (int)
casts in hsync_handler_post() calculations to overflow.
For me, this caused Amiberry to freeze occasionally on Batocera, but not
on Manjaro ARM. I guess this is because Batocera being lighter gives
Amiberry more runtime making it possible to sleep in
hsync_handler_post() loops and getting stuck for a while in those.
(Based on sleep if more than 2ms "free" time comment in the code.)
As read_processor_time() measures microseconds these overflows happen
every 2 ^ 32 microseconds (about 1 h 11 min 35 s). clock_gettime()'s …
> Fix int overflows in hsync_handler_post()

- Makefile
- external/libguisan/Makefile
- make-bundle.sh
- src/fsusage.cpp
- src/jit/compemu_support.cpp
- src/main.cpp
- src/osdep/aarch64_helper_osx.s
- src/osdep/amiberry.cpp
- src/osdep/amiberry_filesys.cpp
- src/osdep/amiberry_gfx.cpp
- src/osdep/amiberry_gui.cpp
- src/osdep/amiberry_hardfile.cpp
- src/osdep/amiberry_mem.cpp
- src/osdep/bsdsocket_host.cpp
- src/osdep/sigsegv_handler.cpp
- src/osdep/sysconfig.h
- src/osdep/target.h
- src/parser.cpp
- src/scp.cpp
- src/zfile.cpp
Fixes for OS X
- Added build platform osx, make PLATFORM=osx will build for Mac OS X 12/12.1 for ARM
- Added aarch64_helper_osx.s with fixes for ARM64 on OS X
- Don't include linux specific include files on OS X
- Fixes for various OS X specific behaviour including difference in the sigsegv handler, serial code and others
- Some changes to SDL2 behaviour on OS X, including enabling High DPI mode by default
- Script for building App bundle on OS X and installing user specific files into Documents/Amiberry
- JIT does not work on OS X due to 32 bit access space dependancy, will crash if enabled
> Ported to OS X for M1 based Macs

- Info.plist.template
- make-bundle.sh
- run_amiberry.zsh
- src/osdep/amiberry.cpp
- Moves macOS environment setup/configuration generation/resource copying from compile time to run time, in order to allow for app bundle distribution to other people
@midwan
> Moved resource creation to runtime

- src/include/options.h
- src/main.cpp
- src/osdep/picasso96.cpp
- src/osdep/target.h
The hardware interrupt was removed during some WinUAE adaptations between 5.1 and 5.2. This caused RTG modes to fail for some hardware, including mine. My machine is a M1 MAX MacBook Pro.
This PR simply adds those lines back in. They seem to work on my machine if done.
Fixes https://github.com/midwan/amiberry/issues/983
* Restore hardware interrupt and fix regression
* Bumped version to 5.2.1
@midwan
> Restore hardware interrupt; fix RTG for M1 MAX and possibly others

- Makefile
- src/main.cpp
- src/osdep/amiberry_filesys.cpp
Fixes # . Added the possibility to compile with a version of GCC older than 8.0 where filesystem is found under
<experimental/filesystem>. Tested on my Linux box (CPU AMD E1) with Mint 19.3 and GCC 7.5
- Makefile Added USE_OLDGCC option
- Main.cpp and amiberry_filesys.cpp fixed define for OLDGCC and also fixed some lines where filesystem where used.
-
@midwan
> Added the possibility to compile with a version of GCC older than 8.0

- make-bundle.sh
protect the MINOR and MAJOR values to remove non-integers
Fixes # 1034
- Remove non numeric vales from the MAJOR and MINOR vars in the make-bundle.sh
@midwan
> Protect Make Bundle

- src/osdep/target.h
Fixes # N/A.
- Updated version number to include a v in front.
Such as v5.7 so the apple build script can sign
as expected.
@midwan
> VersionNumberUpdate

- docs/README.md
Fixes # .
- The APT package is called `libserialport0`:
- https://packages.debian.org/libserialport0
- https://packages.ubuntu.com/libserialport0
@midwan
> Fix libserialport0 APT package name in README.md

- .gitignore
- Brewfile
- This adds a Brewfile, which can install all of the dependencies listed through Homebrew by running a `brew bundle` command.  I'm hoping to get this added and then update the wiki instructions for macOS compilation to use that for dependency installation, to simplify it (and hopefully avoid future instances where the wiki doesn't mention a new dependency, which seems to be the case with `libserialport` currently).
@midwan
> Add Brewfile

- Makefile
- src/include/sysdeps.h
- src/machdep/m68k.h
- src/osdep/sigsegv_handler.cpp
- src/osdep/sysconfig.h
While bringing to Batocera to RISC-V based StarFive VisionFive 2 SBC, I added initial RISC-V 64 support to Amiberry.
- Add riscv64 target in Makefile
- Implement basic riscv64 support in CPU interpreter
- Tested working on StarFive VisionFive 2 SBC (implements RV64GC). 
@midwan please review, also tell me if this should go to upstream WinUAE code or not.
> Initial experimental RISC-V 64bit port. 

- Makefile
- Added support for the Raspberry Pi 5 SBC [1], with the following 'platform' targets:
* `pi5-sdl2` should build a 32bit (armhf) binary
* `pi5-64-sdl2` should build a 64bit (aarch64) binary
Note:
I didn't add any `dispmanx`/`dmx` targets since DispmanX is no longer supported upstream since RaspiOS 11 _bullseye_ and certainly won't work on a 64bit arch (on a Pi4 or otherwise).
Refs:
[1] https://www.raspberrypi.com/products/raspberry-pi-5/
> platforms: add Raspberry Pi5 as a new target

- src/include/options.h
- src/osdep/amiberry.cpp
- src/osdep/gui/ShowMessage.cpp
- src/osdep/gui/gui_handling.h
- src/osdep/gui/main_window.cpp
Fixes #1084
This exports the GUI colors used, as well as the Font name and size, to `amiberry.conf`.
The default values will be used if none exist. If they do exist there, they will be parsed and used instead of the built-in defaults.
This allows users to customize the look of the GUI, with custom colors and fonts.
@midwan
> 1084 expose gui theme

- src/machdep/rpt.h
- src/machdep/support.cpp
No measurable performance change, but makes the code easier to read/maintain.
Also, this syncs this piece of the code with WinUAE
> refactor: use SDL2 functions for calibrating and counting time

- Makefile
- Setting the `CWRAPPER` Makefile variable will prefix gcc/g++ commands with the wrapper. This enables the use of `ccache` which can vastly speed up rebuilds. Tested with `ccache`, but `distcc` and other tools of this kind should work too.
- The `clean` target left behind a directory - fixed this, `make clean` (with the right `PLATFORM` set) now leaves the workspace pristine.
My first contribution to this project (and indeed any open source project in quite a long time!) I hope it is something that the project will find interesting or useful.
@midwan
> Support ccache, distcc etc. in Makefile - and fix files missed from clean target

- CMakeLists.txt
Fixes #1242  .
- Add basic support to detect ARM 32-bit targets
- Add basic support to compile JIT for ARM 32-bit targets
- TODO : detect/enable NEON dynamically in CMake
@midwan
> Add basic support for ARM 32-bit targets in CMake

- CMakeLists.txt
Fixes #1297 .
- Updated CMakeLists.txt to fix the build issue
Thorougly tested for vaious ARM 32-bit targets.
@midwan
> Fix ARM 32-bit build through CMake

- src/osdep/amiberry_filesys.cpp
lstat does not follow symlinks, so if you have a directory symlinked, my_existsdir tells us, it does not exists.
use S_ISREG (== file) instead of !S_ISDIR (==not directory) on regular files. There are more inode-types than files and directories.
Fixes # .
-
-
-
@midwan
> use stat instead of lstat on files and directories

- flatpak/com.blitterstudio.amiberry.desktop
These are also used by Flathub, KDE Discover and Gnome Software
- Add keywords as specified here: https://webcache.googleusercontent.com/search?q=cache:https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
E.g. for [Ghidra](https://flathub.org/apps/org.ghidra_sre.Ghidra), it looks like this:
@midwan
> Add keywords to .desktop file

- macos_init_amiberry.zsh
- src/osdep/amiberry.cpp
> Macos folder changes

- src/osdep/writelog.cpp
- The `fd` command in the debugger didn't work, because the debugger code expects the `d` to be followed by `\0` in the input buffer. Fix amiberry's version of `console_get` to strip newline characters from the end of the string it returns, as the Windows version does (rather than just adjusting the length value).
@midwan
> bugfix: remove newlines from debugger input

- src/osdep/amiberry.cpp
- When the debugger is entered with Shift-F12, `target_inputdevice_unacquire` is called to release the mouse pointer. The second argument to `SDL_SetWindowGrab` should be `SDL_FALSE` to disable the grab; previously, both `_acquire` and `_release` had `SDL_TRUE`, which enables the grab. (v2 against preview rather than master.)
@midwan
> bugfix: release window grab in the debugger

- src/include/options.h
Increase GFX MAX_RTG_Boards to 4 as it looks like Picasso96 code is expecting 4 not the 1 listed.
Fixes # .
Increase number of MAX_RTG_Boards defined to 4 as the Picasso96.cpp file looks like it is trying to set data for 4 and with the previous 1 looks like a possible buffer overflow.
This single change corrected all issues with MacOS 15 with a M1 and looks like minimal to no impact.
@midwan
> Picasso GFX MAX_RTG_Board # change

- CMakeLists.txt
- src/osdep/amiberry.cpp
- The new installation rules respect `CMAKE_INSTALL_PREFIX`, but the install prefix was hardcoded as `/usr` in several places in `osdep/amiberry.cpp`. Define `AMIBERRY_DATADIR` and `AMIBERRY_LIBDIR` in `CMakeLists.txt`, and use these instead of the hardcoded paths, so amiberry will work correctly for any prefix.
@midwan
> build: don't hardcode /usr prefix in the source

- flatpak/com.blitterstudio.amiberry.yml
- src/osdep/amiberry.cpp
These variables are defined in the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/latest/).
Previously, if `XDG_DATA_HOME` or `XDG_CONFIG_HOME` were defined, amiberry would store data and config files directly in those directories. This is nonstandard -- defining these variables will change the behaviour of other programs too, and programs should use a subdirectory if they're storing multiple files.
After this commit, amiberry now computes the standard default values for these variables based on `HOME` if they aren't defined, and checks to see whether `XDG_DATA_HOME/amiberry` and `XDG_CONFIG_HOME/amiberry` exist. If they do, then they will be used as amiberry's home directory and config directory respectively …
> Use XDG_*_HOME in a more standard way

- src/osdep/amiberry_input.cpp
Improve releasing of Alt-Tab keys when releasing capture.
Apparently in some distros, we still had those keys stuck as "pressed" when we got back to Amiberry.
Hopefully this should improve things
> Alt tab fixes

- cmake/SourceFiles.cmake
- external/libguisan/include/guisan/listmodel.hpp
- src/cfgfile.cpp
- src/include/uae.h
- src/ini.cpp
- src/osdep/amiberry.cpp
- src/osdep/amiberry_gui.cpp
- src/osdep/amiberry_whdbooter.cpp
- src/osdep/gui/PanelExpansions.cpp
- src/osdep/gui/PanelPaths.cpp
- src/osdep/gui/PanelROM.cpp
- src/osdep/gui/StringListModel.h
- src/osdep/gui/gui_handling.h
- src/osdep/registry.cpp
- src/osdep/registry.h
- src/osdep/target.h
Fixes #1480 
- Refactored the way ROMs are scanned, to match WinUAE
- The `DetectedROMs` section is now saved to a separate file: `$XDG_CONFIG_HOME/amiberry.ini`. The format of the entries matches that of WinUAE (including the ROM ids), in order to make things work without having to change everything around
- Fixed a few bugs in the StringListModel, which became apparent while working on this solution
- Create the XDG_* directories on startup, if they don't exist. This happened at least once in WSL2 + Debian12
- Enabled support for multiple RTG boards in the cfgfile
- Implemented (hopefully) all of the functionality of the Expansion panel, matching the equivalent on WinUAE.
@midwan
> 1480 implement missing features in expansion gui panel

- src/osdep/amiberry.cpp
Looks like `path` was used before being initialized here. I replaced the call to `_tcscpy` with one to `my_strdup` instead.
@midwan
> bugfix: Fixed uninitialized path variable

- src/osdep/ahi_v1.cpp
- src/osdep/amiberry_serial.cpp
- src/parser.cpp
Fixes #1513 
Probably not entirely correct still, but at least it won't trigger crashes due to increasing memory usage anymore.
> 1513 excessive calls to sdl queueaudio when using ahi

- src/osdep/amiberry.cpp
Fixes #1527 
- Check for the existence of a file named "amiberry.portable" in the current directory, when starting up. If found, switch to portable mode, expecting all related directories under the current dir.
@midwan
> enhancement: added portable mode detection (fixes #1527)

- .github/workflows/c-cpp.yml
- cmake/macos/CMakeLists.txt
- src/osdep/amiberry.cpp
The bundled plugins of capsimg and floppybridge, were not included in the final app bundle. Furthermore, they need to be signed with the same digital certificate, otherwise MacOS will block them from loading.
Fixes #1540 .
- include bundled plugins in a separate folder
- digitally sign bundled plugins during the build step
- during the first run, if the plugins directory did not exist, copy the bundled files in there as well.
@midwan
> bugfix: fix bundled plugins on MacOS (#1540)

- src/cfgfile.cpp
- src/include/options.h
> bugfix: whdload filename was not retained in configs (fixes #1539)

- src/main.cpp
- src/osdep/amiberry.cpp
- src/osdep/amiberry_gui.cpp
- src/osdep/gui/PanelSavestate.cpp
> 1545 savestates fixes

- src/main.cpp
Fixes conflict with the -m flag to use directory hard drives.
> Remove conflicting -m flag from model config

- src/osdep/amiberry_serial.cpp
I tried using TCP serial port functionality and found that it would never end up listening on the port
After some digging I've traced it down to this:
Here in `openser()`, `sername` is passed to `opentcp()` skipping the "TCP://" part
https://github.com/BlitterStudio/amiberry/blob/8196671d573c07d45fa90f9d3d55d3e67d4ad959/src/osdep/amiberry_serial.cpp#L338C1-L345C3
`opentcp()` calls `uae_tcp_listen_uri()` which expects the protocol to be part of the URI, otherwise it returns with `UAE_SOCKET_INVALID`
https://github.com/BlitterStudio/amiberry/blob/8196671d573c07d45fa90f9d3d55d3e67d4ad959/src/osdep/socket.cpp#L131C1-L137C3
This pull request fixes this issue by passing the full sername through to opentcp
> Fix tcp serial ports

- cmake/Dependencies.cmake
- packaging/CMakeLists.txt
- src/archivers/chd/chdcodec.cpp
- src/archivers/chd/chdcodec.h
- src/main.cpp
- Adds support for zstd / cdzs compression in CHD format 
- Adjust CMake packaging 
- Fix buffer overflow detected in gdb when using --cdimage option
@midwan
> Add CHD-zstd support

- src/calc.cpp
- src/kbmcu/m6805/m68_internal.h
- src/pcem/vid_cl5429.cpp
- src/pcem/vid_ncr.cpp
- src/pcem/vid_permedia2.cpp
- src/pcem/vid_s3.cpp
- src/pcem/vid_voodoo_banshee.cpp
- src/pcem/x86seg.cpp
Fixes the typical string constant conversion warnings if former C code is compiled by a C++ compiler.
warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
@midwan
> Fix all C++ string constant conversion warnings

- src/a2065.cpp
- src/akiko.cpp
- src/blkdev_cdimage.cpp
- src/cd32_fmv.cpp
- src/cdtv.cpp
- src/cdtvcr.cpp
- src/include/commpipe.h
- src/native2amiga.cpp
- src/osdep/cda_play.cpp
- src/qemuvga/ne2000.cpp
warning: using value of assignment with ‘volatile’-qualified left
operand is deprecated [-Wvolatile]
Chained assignments of volatile variables (var1 = var2 = var3 = 0;) result in a read-modify-write opcode chain which breaks the idea behind using volatile. Here during the modify phase the volatile variable can be modified by an external source (the software running inside the emulator), then the volatile variable is written again with the former read value, completely dropping the value from the external source. It is a rare scenario, but it happens, hence the warning from the compiler. The fix is easy, break up the chained assignments.
@midwan
> fix all volatile variable breaking chained assignments

- src/jit/x86/exception_handler.cpp
- src/osdep/sysconfig.h
- src/vm.cpp
Fixes # .
-added a needed hint and MAP_32BIT flag for FreeBSD
-added a CONTEXT_T layout supported by fbsd x86 ucontext
-these changes should be enough to get jit working on a fbsd x86_64 system
@midwan
This PR is generously sponsored by @ut316ab
> changes for JIT support for freebsd x86_64
